package rule

import "github.com/didebughu/go-grepper/internal/model"

func init() {
	// CPP 规则
	Register(&Rule{ID: "CPP-MEMLK-001", Name: "Potential Memory Leak", Severity: model.SeverityHigh, Languages: []string{"cpp"}, Category: "MEMLK", Enabled: true})
	Register(&Rule{ID: "CPP-BUFOV-001", Name: "malloc Fixed Value", Severity: model.SeverityMedium, Languages: []string{"cpp"}, Category: "BUFOV", Enabled: true})
	Register(&Rule{ID: "CPP-BUFOV-002", Name: "Potential Buffer Overflow", Severity: model.SeverityHigh, Languages: []string{"cpp"}, Category: "BUFOV", Enabled: true})
	Register(&Rule{ID: "CPP-SIGN-001", Name: "Signed/Unsigned Comparison", Severity: model.SeverityHigh, Languages: []string{"cpp"}, Category: "SIGN", Enabled: true})
	Register(&Rule{ID: "CPP-MISC-001", Name: "Potential Misuse of Safe Function", Severity: model.SeverityHigh, Languages: []string{"cpp"}, Category: "MISC", Enabled: true})
	Register(&Rule{ID: "CPP-RESRC-001", Name: "Exception Throw in Destructor", Severity: model.SeverityStandard, Languages: []string{"cpp"}, Category: "RESRC", Enabled: true})
	Register(&Rule{ID: "CPP-RACE-001", Name: "Potential TOCTOU Vulnerability", Severity: model.SeverityStandard, Languages: []string{"cpp"}, Category: "RACE", Enabled: true})
	Register(&Rule{ID: "CPP-MISC-002", Name: "printf Format String Vulnerability", Severity: model.SeverityHigh, Languages: []string{"cpp"}, Category: "MISC", Enabled: true})
	Register(&Rule{ID: "CPP-TMPF-001", Name: "Unsafe Temporary File Allocation", Severity: model.SeverityMedium, Languages: []string{"cpp"}, Category: "TMPF", Enabled: true})
	Register(&Rule{ID: "CPP-MEMLK-002", Name: "Dangerous Use of realloc", Severity: model.SeverityMedium, Languages: []string{"cpp"}, Category: "MEMLK", Enabled: true})
	Register(&Rule{ID: "CPP-CMDI-001", Name: "User Controlled Variable on Command Line", Severity: model.SeverityHigh, Languages: []string{"cpp"}, Category: "CMDI", Enabled: true})
	Register(&Rule{ID: "CPP-CMDI-002", Name: "Application Variable on Command Line", Severity: model.SeverityMedium, Languages: []string{"cpp"}, Category: "CMDI", Enabled: true})

	// Java 规则
	Register(&Rule{ID: "JAVA-MISC-001", Name: "Thread.sleep in Servlet", Severity: model.SeverityStandard, Languages: []string{"java"}, Category: "MISC", Enabled: true})
	Register(&Rule{ID: "JAVA-SQLI-001", Name: "SQL Injection (Dynamic)", Severity: model.SeverityCritical, Languages: []string{"java"}, Category: "SQLI", Enabled: true})
	Register(&Rule{ID: "JAVA-SQLI-002", Name: "SQL Injection (Pre-prepared)", Severity: model.SeverityCritical, Languages: []string{"java"}, Category: "SQLI", Enabled: true})
	Register(&Rule{ID: "JAVA-XSS-001", Name: "XSS (JSP getParameter)", Severity: model.SeverityHigh, Languages: []string{"java"}, Category: "XSS", Enabled: true})
	Register(&Rule{ID: "JAVA-XSS-002", Name: "XSS (HttpServletRequest)", Severity: model.SeverityHigh, Languages: []string{"java"}, Category: "XSS", Enabled: true})
	Register(&Rule{ID: "JAVA-XSS-003", Name: "XSS (Session Variable)", Severity: model.SeverityHigh, Languages: []string{"java"}, Category: "XSS", Enabled: true})
	Register(&Rule{ID: "JAVA-XSS-004", Name: "XSS (escapeXML=false)", Severity: model.SeverityHigh, Languages: []string{"java"}, Category: "XSS", Enabled: true})
	Register(&Rule{ID: "JAVA-INPUT-001", Name: "Poor Input Validation", Severity: model.SeverityHigh, Languages: []string{"java"}, Category: "INPUT", Enabled: true})
	Register(&Rule{ID: "JAVA-CMDI-001", Name: "Runtime.exec Variable Path", Severity: model.SeverityHigh, Languages: []string{"java"}, Category: "CMDI", Enabled: true})
	Register(&Rule{ID: "JAVA-NET-001", Name: "URL Request over HTTP", Severity: model.SeverityStandard, Languages: []string{"java"}, Category: "NET", Enabled: true})
	Register(&Rule{ID: "JAVA-NET-002", Name: "URL Request Variable Path", Severity: model.SeverityStandard, Languages: []string{"java"}, Category: "NET", Enabled: true})
	Register(&Rule{ID: "JAVA-SERIAL-001", Name: "Class Implements Clone", Severity: model.SeverityMedium, Languages: []string{"java"}, Category: "SERIAL", Enabled: true})
	Register(&Rule{ID: "JAVA-SERIAL-002", Name: "Class Implements Serialization", Severity: model.SeverityMedium, Languages: []string{"java"}, Category: "SERIAL", Enabled: true})
	Register(&Rule{ID: "JAVA-SERIAL-003", Name: "Class Implements Deserialization", Severity: model.SeverityMedium, Languages: []string{"java"}, Category: "SERIAL", Enabled: true})
	Register(&Rule{ID: "JAVA-PRIV-001", Name: "Public Variable in Class", Severity: model.SeverityStandard, Languages: []string{"java"}, Category: "PRIV", Enabled: true})
	Register(&Rule{ID: "JAVA-PRIV-002", Name: "Public Class Not Final", Severity: model.SeverityPossiblySafe, Languages: []string{"java"}, Category: "PRIV", Enabled: true})
	Register(&Rule{ID: "JAVA-TMPF-001", Name: "Unsafe Temporary File Allocation", Severity: model.SeverityMedium, Languages: []string{"java"}, Category: "TMPF", Enabled: true})
	Register(&Rule{ID: "JAVA-CONF-001", Name: "XML Entity Expansion", Severity: model.SeverityStandard, Languages: []string{"java"}, Category: "CONF", Enabled: true})
	Register(&Rule{ID: "JAVA-INTOV-001", Name: "Primitive Data Type Operation", Severity: model.SeverityLow, Languages: []string{"java"}, Category: "INTOV", Enabled: true})
	Register(&Rule{ID: "JAVA-RESRC-001", Name: "Failure to Release Resources", Severity: model.SeverityMedium, Languages: []string{"java"}, Category: "RESRC", Enabled: true})
	Register(&Rule{ID: "JAVA-RESRC-002", Name: "FileStream Without Exception Handling", Severity: model.SeverityMedium, Languages: []string{"java"}, Category: "RESRC", Enabled: true})
	Register(&Rule{ID: "JAVA-CRYPTO-001", Name: "Static Crypto Keys (Android)", Severity: model.SeverityHigh, Languages: []string{"java"}, Category: "CRYPTO", Enabled: true})

	// C# 规则
	Register(&Rule{ID: "CS-INPUT-001", Name: "Input Validation Disabled", Severity: model.SeverityHigh, Languages: []string{"csharp"}, Category: "INPUT", Enabled: true})
	Register(&Rule{ID: "CS-SQLI-001", Name: "SQL Injection (Dynamic)", Severity: model.SeverityCritical, Languages: []string{"csharp", "vb"}, Category: "SQLI", Enabled: true})
	Register(&Rule{ID: "CS-SQLI-002", Name: "SQL Injection (Pre-prepared)", Severity: model.SeverityCritical, Languages: []string{"csharp", "vb"}, Category: "SQLI", Enabled: true})
	Register(&Rule{ID: "CS-XSS-001", Name: "XSS (Response.Write)", Severity: model.SeverityHigh, Languages: []string{"csharp", "vb"}, Category: "XSS", Enabled: true})
	Register(&Rule{ID: "CS-XSS-002", Name: "XSS (Html.Raw)", Severity: model.SeverityHigh, Languages: []string{"csharp", "vb"}, Category: "XSS", Enabled: true})
	Register(&Rule{ID: "CS-XSS-003", Name: "XSS (Label)", Severity: model.SeverityHigh, Languages: []string{"csharp", "vb"}, Category: "XSS", Enabled: true})
	Register(&Rule{ID: "CS-CRYPTO-001", Name: "Insecure Storage of Sensitive Info", Severity: model.SeverityMedium, Languages: []string{"csharp", "vb"}, Category: "CRYPTO", Enabled: true})
	Register(&Rule{ID: "CS-INTOV-001", Name: "Integer Operation Unchecked", Severity: model.SeverityStandard, Languages: []string{"csharp"}, Category: "INTOV", Enabled: true})
	Register(&Rule{ID: "CS-INTOV-002", Name: "Integer Overflow Check Disabled", Severity: model.SeverityStandard, Languages: []string{"csharp"}, Category: "INTOV", Enabled: true})
	Register(&Rule{ID: "CS-LOG-001", Name: "Log User Passwords", Severity: model.SeverityHigh, Languages: []string{"csharp", "vb"}, Category: "LOG", Enabled: true})
	Register(&Rule{ID: "CS-LOG-002", Name: "Unsanitized Data in Logs", Severity: model.SeverityMedium, Languages: []string{"csharp", "vb"}, Category: "LOG", Enabled: true})
	Register(&Rule{ID: "CS-RACE-001", Name: "Potential TOCTOU Vulnerability", Severity: model.SeverityStandard, Languages: []string{"csharp", "vb"}, Category: "RACE", Enabled: true})
	Register(&Rule{ID: "CS-REDIR-001", Name: "URL Request over HTTP", Severity: model.SeverityStandard, Languages: []string{"csharp", "vb"}, Category: "REDIR", Enabled: true})
	Register(&Rule{ID: "CS-REDIR-002", Name: "URL Redirect from Unvalidated Variable", Severity: model.SeverityMedium, Languages: []string{"csharp", "vb"}, Category: "REDIR", Enabled: true})
	Register(&Rule{ID: "CS-REDIR-003", Name: "URL Redirect from Variable", Severity: model.SeverityStandard, Languages: []string{"csharp", "vb"}, Category: "REDIR", Enabled: true})
	Register(&Rule{ID: "CS-RAND-001", Name: "Deterministic Pseudo-Random Values", Severity: model.SeverityMedium, Languages: []string{"csharp"}, Category: "RAND", Enabled: true})
	Register(&Rule{ID: "CS-TMPF-001", Name: "Unsafe Temporary File Allocation", Severity: model.SeverityMedium, Languages: []string{"csharp"}, Category: "TMPF", Enabled: true})
	Register(&Rule{ID: "CS-MISC-001", Name: "Unsafe Code Directive", Severity: model.SeverityMedium, Languages: []string{"csharp"}, Category: "MISC", Enabled: true})
	Register(&Rule{ID: "CS-CMDI-001", Name: "User Controlled Variable on Command Line", Severity: model.SeverityHigh, Languages: []string{"csharp", "vb"}, Category: "CMDI", Enabled: true})
	Register(&Rule{ID: "CS-CMDI-002", Name: "Application Variable on Command Line", Severity: model.SeverityMedium, Languages: []string{"csharp", "vb"}, Category: "CMDI", Enabled: true})
	Register(&Rule{ID: "CS-CONF-001", Name: ".NET Default Errors Enabled", Severity: model.SeverityMedium, Languages: []string{"csharp", "vb"}, Category: "CONF", Enabled: true})
	Register(&Rule{ID: "CS-CONF-002", Name: ".NET Debugging Enabled", Severity: model.SeverityMedium, Languages: []string{"csharp", "vb"}, Category: "CONF", Enabled: true})
	Register(&Rule{ID: "CS-PASSWD-001", Name: "Unsafe Password Management", Severity: model.SeverityMedium, Languages: []string{"csharp"}, Category: "PASSWD", Enabled: true})
	Register(&Rule{ID: "CS-MISC-002", Name: "Unsafe Code Block Not Closed", Severity: model.SeverityMedium, Languages: []string{"csharp"}, Category: "MISC", Enabled: true})

	// VB 规则
	Register(&Rule{ID: "VB-RAND-001", Name: "Deterministic Pseudo-Random Values (Rnd)", Severity: model.SeverityMedium, Languages: []string{"vb"}, Category: "RAND", Enabled: true})
	Register(&Rule{ID: "VB-AUTH-001", Name: "Insufficient SAML2 Validation", Severity: model.SeverityMedium, Languages: []string{"vb"}, Category: "AUTH", Enabled: true})
	Register(&Rule{ID: "VB-TMPF-001", Name: "Unsafe Temporary File Allocation", Severity: model.SeverityMedium, Languages: []string{"vb"}, Category: "TMPF", Enabled: true})
	Register(&Rule{ID: "VB-CRYPTO-001", Name: "Hardcoded Crypto Key", Severity: model.SeverityMedium, Languages: []string{"vb"}, Category: "CRYPTO", Enabled: true})
	Register(&Rule{ID: "VB-PASSWD-001", Name: "Unsafe Password Management", Severity: model.SeverityMedium, Languages: []string{"vb"}, Category: "PASSWD", Enabled: true})

	// PHP 规则
	Register(&Rule{ID: "PHP-SQLI-001", Name: "SQL Injection (Dynamic)", Severity: model.SeverityCritical, Languages: []string{"php"}, Category: "SQLI", Enabled: true})
	Register(&Rule{ID: "PHP-SQLI-002", Name: "SQL Injection (Pre-prepared)", Severity: model.SeverityCritical, Languages: []string{"php"}, Category: "SQLI", Enabled: true})
	Register(&Rule{ID: "PHP-XSS-001", Name: "XSS (Super Global)", Severity: model.SeverityHigh, Languages: []string{"php"}, Category: "XSS", Enabled: true})
	Register(&Rule{ID: "PHP-XSS-002", Name: "XSS (User Variable)", Severity: model.SeverityHigh, Languages: []string{"php"}, Category: "XSS", Enabled: true})
	Register(&Rule{ID: "PHP-XSS-003", Name: "DOM-Based XSS", Severity: model.SeverityHigh, Languages: []string{"php"}, Category: "XSS", Enabled: true})
	Register(&Rule{ID: "PHP-LOG-001", Name: "Log User Passwords", Severity: model.SeverityHigh, Languages: []string{"php"}, Category: "LOG", Enabled: true})
	Register(&Rule{ID: "PHP-LOG-002", Name: "Unsanitized Data in Logs", Severity: model.SeverityMedium, Languages: []string{"php"}, Category: "LOG", Enabled: true})
	Register(&Rule{ID: "PHP-RAND-001", Name: "Deterministic Pseudo-Random (openssl false)", Severity: model.SeverityMedium, Languages: []string{"php"}, Category: "RAND", Enabled: true})
	Register(&Rule{ID: "PHP-RAND-002", Name: "Deterministic Pseudo-Random (mt_rand)", Severity: model.SeverityMedium, Languages: []string{"php"}, Category: "RAND", Enabled: true})
	Register(&Rule{ID: "PHP-FILE-001", Name: "Unsafe $_FILES Processing", Severity: model.SeverityMedium, Languages: []string{"php"}, Category: "FILE", Enabled: true})
	Register(&Rule{ID: "PHP-FILE-002", Name: "File Inclusion Vulnerability", Severity: model.SeverityHigh, Languages: []string{"php"}, Category: "FILE", Enabled: true})
	Register(&Rule{ID: "PHP-FILE-003", Name: "Unsafe File Extension Include", Severity: model.SeverityHigh, Languages: []string{"php"}, Category: "FILE", Enabled: true})
	Register(&Rule{ID: "PHP-FILE-004", Name: "File Access Vulnerability", Severity: model.SeverityHigh, Languages: []string{"php"}, Category: "FILE", Enabled: true})
	Register(&Rule{ID: "PHP-CMDI-001", Name: "User Controlled Variable on Command Line", Severity: model.SeverityHigh, Languages: []string{"php"}, Category: "CMDI", Enabled: true})
	Register(&Rule{ID: "PHP-CMDI-002", Name: "Application Variable on Command Line", Severity: model.SeverityMedium, Languages: []string{"php"}, Category: "CMDI", Enabled: true})
	Register(&Rule{ID: "PHP-CMDI-003", Name: "Backtick Command Execution (Super Global)", Severity: model.SeverityHigh, Languages: []string{"php"}, Category: "CMDI", Enabled: true})
	Register(&Rule{ID: "PHP-CMDI-004", Name: "Backtick Command Execution (Variable)", Severity: model.SeverityHigh, Languages: []string{"php"}, Category: "CMDI", Enabled: true})
	Register(&Rule{ID: "PHP-CONF-001", Name: "register_globals Enabled", Severity: model.SeverityCritical, Languages: []string{"php"}, Category: "CONF", Enabled: true})
	Register(&Rule{ID: "PHP-CONF-002", Name: "Indiscriminate Input Variable Merging", Severity: model.SeverityHigh, Languages: []string{"php"}, Category: "CONF", Enabled: true})
	Register(&Rule{ID: "PHP-CONF-003", Name: "Unsafe parse_str", Severity: model.SeverityCritical, Languages: []string{"php"}, Category: "CONF", Enabled: true})
	Register(&Rule{ID: "PHP-CONF-004", Name: "php.ini register_globals On", Severity: model.SeverityCritical, Languages: []string{"php"}, Category: "CONF", Enabled: true})
	Register(&Rule{ID: "PHP-CONF-005", Name: "php.ini safe_mode Off", Severity: model.SeverityMedium, Languages: []string{"php"}, Category: "CONF", Enabled: true})
	Register(&Rule{ID: "PHP-CONF-006", Name: "php.ini magic_quotes Off", Severity: model.SeverityHigh, Languages: []string{"php"}, Category: "CONF", Enabled: true})
	Register(&Rule{ID: "PHP-CONF-007", Name: "php.ini MySQL Root Login", Severity: model.SeverityHigh, Languages: []string{"php"}, Category: "CONF", Enabled: true})
	Register(&Rule{ID: "PHP-CONF-008", Name: "No Disabled Functions", Severity: model.SeverityLow, Languages: []string{"php"}, Category: "CONF", Enabled: true})
	Register(&Rule{ID: "PHP-PASSWD-001", Name: "Unsafe Password Management", Severity: model.SeverityMedium, Languages: []string{"php"}, Category: "PASSWD", Enabled: true})

	// PL/SQL 规则
	Register(&Rule{ID: "PLSQL-CRYPTO-001", Name: "Password Without Encryption", Severity: model.SeverityHigh, Languages: []string{"plsql"}, Category: "CRYPTO", Enabled: true})
	Register(&Rule{ID: "PLSQL-CRYPTO-002", Name: "Password Without Encryption (File)", Severity: model.SeverityHigh, Languages: []string{"plsql"}, Category: "CRYPTO", Enabled: true})
	Register(&Rule{ID: "PLSQL-SQLI-001", Name: "SQL Injection (Variable Concat)", Severity: model.SeverityCritical, Languages: []string{"plsql"}, Category: "SQLI", Enabled: true})
	Register(&Rule{ID: "PLSQL-SQLI-002", Name: "SQL Injection (Input Variable)", Severity: model.SeverityCritical, Languages: []string{"plsql"}, Category: "SQLI", Enabled: true})
	Register(&Rule{ID: "PLSQL-PRIV-001", Name: "Excessive Permissions (AUTHID DEFINER)", Severity: model.SeverityStandard, Languages: []string{"plsql"}, Category: "PRIV", Enabled: true})
	Register(&Rule{ID: "PLSQL-PRIV-002", Name: "Excessive Permissions (No AUTHID)", Severity: model.SeverityStandard, Languages: []string{"plsql"}, Category: "PRIV", Enabled: true})
	Register(&Rule{ID: "PLSQL-RESRC-001", Name: "COMMIT/ROLLBACK Without PRAGMA", Severity: model.SeverityLow, Languages: []string{"plsql"}, Category: "RESRC", Enabled: true})
	Register(&Rule{ID: "PLSQL-MISC-001", Name: "Error Handling With Output Parameters", Severity: model.SeverityMedium, Languages: []string{"plsql"}, Category: "MISC", Enabled: true})
	Register(&Rule{ID: "PLSQL-MISC-002", Name: "Data Formatting Within VIEW", Severity: model.SeverityStandard, Languages: []string{"plsql"}, Category: "MISC", Enabled: true})

	// COBOL 规则
	Register(&Rule{ID: "COBOL-MISC-001", Name: "File Has No PROGRAM-ID", Severity: model.SeverityLow, Languages: []string{"cobol"}, Category: "MISC", Enabled: true})
	Register(&Rule{ID: "COBOL-MISC-002", Name: "Filename Does Not Match PROGRAM-ID", Severity: model.SeverityLow, Languages: []string{"cobol"}, Category: "MISC", Enabled: true})
	Register(&Rule{ID: "COBOL-MISC-003", Name: "PROGRAM-ID Includes File Extension", Severity: model.SeverityLow, Languages: []string{"cobol"}, Category: "MISC", Enabled: true})
	Register(&Rule{ID: "COBOL-MISC-004", Name: "Multiple Use of PROGRAM-ID", Severity: model.SeverityLow, Languages: []string{"cobol"}, Category: "MISC", Enabled: true})
	Register(&Rule{ID: "COBOL-CMDI-001", Name: "CICS Output Redirection", Severity: model.SeverityHigh, Languages: []string{"cobol"}, Category: "CMDI", Enabled: true})
	Register(&Rule{ID: "COBOL-CMDI-002", Name: "Unsafe Command within CICS", Severity: model.SeverityStandard, Languages: []string{"cobol"}, Category: "CMDI", Enabled: true})
	Register(&Rule{ID: "COBOL-SQLI-001", Name: "User Variable in SQL Statement", Severity: model.SeverityHigh, Languages: []string{"cobol"}, Category: "SQLI", Enabled: true})
	Register(&Rule{ID: "COBOL-BUFOV-001", Name: "PIC Length Mismatch", Severity: model.SeverityHigh, Languages: []string{"cobol"}, Category: "BUFOV", Enabled: true})
	Register(&Rule{ID: "COBOL-SIGN-001", Name: "PIC Sign Mismatch", Severity: model.SeverityHigh, Languages: []string{"cobol"}, Category: "SIGN", Enabled: true})
	Register(&Rule{ID: "COBOL-SIGN-002", Name: "PIC Type Mismatch", Severity: model.SeverityHigh, Languages: []string{"cobol"}, Category: "SIGN", Enabled: true})
	Register(&Rule{ID: "COBOL-FILE-001", Name: "User Controlled File/Directory Name", Severity: model.SeverityLow, Languages: []string{"cobol"}, Category: "FILE", Enabled: true})
	Register(&Rule{ID: "COBOL-LOG-001", Name: "Log User Passwords", Severity: model.SeverityHigh, Languages: []string{"cobol"}, Category: "LOG", Enabled: true})
	Register(&Rule{ID: "COBOL-LOG-002", Name: "Unsanitized Data in Logs", Severity: model.SeverityMedium, Languages: []string{"cobol"}, Category: "LOG", Enabled: true})
	Register(&Rule{ID: "COBOL-RACE-001", Name: "Potential TOCTOU Vulnerability", Severity: model.SeverityStandard, Languages: []string{"cobol"}, Category: "RACE", Enabled: true})
	Register(&Rule{ID: "COBOL-RAND-001", Name: "Deterministic Pseudo-Random Values", Severity: model.SeverityStandard, Languages: []string{"cobol"}, Category: "RAND", Enabled: true})
	Register(&Rule{ID: "COBOL-TMPF-001", Name: "Unsafe Temporary File Allocation", Severity: model.SeverityMedium, Languages: []string{"cobol"}, Category: "TMPF", Enabled: true})
	Register(&Rule{ID: "COBOL-CMDI-003", Name: "User Variable for Dynamic Call", Severity: model.SeverityHigh, Languages: []string{"cobol"}, Category: "CMDI", Enabled: true})
	Register(&Rule{ID: "COBOL-CMDI-004", Name: "Dynamic Function Call", Severity: model.SeverityMedium, Languages: []string{"cobol"}, Category: "CMDI", Enabled: true})
	Register(&Rule{ID: "COBOL-CMDI-005", Name: "User Variable as Call Parameter", Severity: model.SeverityLow, Languages: []string{"cobol"}, Category: "CMDI", Enabled: true})
	Register(&Rule{ID: "COBOL-PASSWD-001", Name: "Unsafe Password Management", Severity: model.SeverityMedium, Languages: []string{"cobol"}, Category: "PASSWD", Enabled: true})

	// R 规则
	Register(&Rule{ID: "R-DATA-001", Name: "Registry Value in Variable", Severity: model.SeverityMedium, Languages: []string{"r"}, Category: "DATA", Enabled: true})
	Register(&Rule{ID: "R-DATA-002", Name: "Excel Data in Variable", Severity: model.SeverityMedium, Languages: []string{"r"}, Category: "DATA", Enabled: true})
	Register(&Rule{ID: "R-DATA-003", Name: "Excel File Use", Severity: model.SeverityLow, Languages: []string{"r"}, Category: "DATA", Enabled: true})
	Register(&Rule{ID: "R-DATA-004", Name: "Data Imported from Package", Severity: model.SeverityInfo, Languages: []string{"r"}, Category: "DATA", Enabled: true})
	Register(&Rule{ID: "R-DATA-005", Name: "Data Imported from R Dataset", Severity: model.SeverityLow, Languages: []string{"r"}, Category: "DATA", Enabled: true})
	Register(&Rule{ID: "R-DATA-006", Name: "Data Saved to R Dataset", Severity: model.SeverityLow, Languages: []string{"r"}, Category: "DATA", Enabled: true})
	Register(&Rule{ID: "R-NET-001", Name: "Unencrypted Connection", Severity: model.SeverityMedium, Languages: []string{"r"}, Category: "NET", Enabled: true})
	Register(&Rule{ID: "R-NET-002", Name: "Data Imported from HTML Table", Severity: model.SeverityLow, Languages: []string{"r"}, Category: "NET", Enabled: true})
	Register(&Rule{ID: "R-NET-003", Name: "HTML Scraped from Web Page", Severity: model.SeverityLow, Languages: []string{"r"}, Category: "NET", Enabled: true})
	Register(&Rule{ID: "R-NET-004", Name: "Data Imported Over Network", Severity: model.SeverityMedium, Languages: []string{"r"}, Category: "NET", Enabled: true})
	Register(&Rule{ID: "R-NET-005", Name: "Data Exported Over Network", Severity: model.SeverityMedium, Languages: []string{"r"}, Category: "NET", Enabled: true})
	Register(&Rule{ID: "R-CRYPTO-001", Name: "Database Password Disclosed", Severity: model.SeverityHigh, Languages: []string{"r"}, Category: "CRYPTO", Enabled: true})
	Register(&Rule{ID: "R-DATA-007", Name: "JSON Data Imported", Severity: model.SeverityInfo, Languages: []string{"r"}, Category: "DATA", Enabled: true})
	Register(&Rule{ID: "R-DATA-008", Name: "XML Data Imported", Severity: model.SeverityInfo, Languages: []string{"r"}, Category: "DATA", Enabled: true})
	Register(&Rule{ID: "R-DATA-009", Name: "Data Saved to XML", Severity: model.SeverityLow, Languages: []string{"r"}, Category: "DATA", Enabled: true})
	Register(&Rule{ID: "R-SERIAL-001", Name: "Object Deserialization", Severity: model.SeverityStandard, Languages: []string{"r"}, Category: "SERIAL", Enabled: true})
	Register(&Rule{ID: "R-SERIAL-002", Name: "Object Serialized to Disc", Severity: model.SeverityStandard, Languages: []string{"r"}, Category: "SERIAL", Enabled: true})
	Register(&Rule{ID: "R-FILE-001", Name: "File Input in Variable", Severity: model.SeverityMedium, Languages: []string{"r"}, Category: "FILE", Enabled: true})
	Register(&Rule{ID: "R-FILE-002", Name: "External File Input", Severity: model.SeverityLow, Languages: []string{"r"}, Category: "FILE", Enabled: true})
	Register(&Rule{ID: "R-CMDI-001", Name: "System Command via cat pipe", Severity: model.SeverityHigh, Languages: []string{"r"}, Category: "CMDI", Enabled: true})
	Register(&Rule{ID: "R-FILE-003", Name: "Data Saved to File", Severity: model.SeverityLow, Languages: []string{"r"}, Category: "FILE", Enabled: true})
	Register(&Rule{ID: "R-DATA-010", Name: "Clipboard Content in Variable", Severity: model.SeverityMedium, Languages: []string{"r"}, Category: "DATA", Enabled: true})
	Register(&Rule{ID: "R-DATA-011", Name: "Clipboard Content Use", Severity: model.SeverityMedium, Languages: []string{"r"}, Category: "DATA", Enabled: true})
	Register(&Rule{ID: "R-TMPF-001", Name: "Unsafe Temporary Directory Use", Severity: model.SeverityMedium, Languages: []string{"r"}, Category: "TMPF", Enabled: true})
	Register(&Rule{ID: "R-FILE-004", Name: "Unsafe File Write", Severity: model.SeverityMedium, Languages: []string{"r"}, Category: "FILE", Enabled: true})
	Register(&Rule{ID: "R-FILE-005", Name: "User-Controlled Path", Severity: model.SeverityMedium, Languages: []string{"r"}, Category: "FILE", Enabled: true})
	Register(&Rule{ID: "R-RACE-001", Name: "Potential TOCTOU Vulnerability", Severity: model.SeverityStandard, Languages: []string{"r"}, Category: "RACE", Enabled: true})
	Register(&Rule{ID: "R-CMDI-002", Name: "System Shell/Command (User Variable)", Severity: model.SeverityHigh, Languages: []string{"r"}, Category: "CMDI", Enabled: true})
	Register(&Rule{ID: "R-CMDI-003", Name: "System Shell/Command", Severity: model.SeverityMedium, Languages: []string{"r"}, Category: "CMDI", Enabled: true})
	Register(&Rule{ID: "R-MISC-001", Name: "Environment Variable Use", Severity: model.SeverityMedium, Languages: []string{"r"}, Category: "MISC", Enabled: true})
	Register(&Rule{ID: "R-INPUT-001", Name: "Direct Input From User (Variable)", Severity: model.SeverityHigh, Languages: []string{"r"}, Category: "INPUT", Enabled: true})
	Register(&Rule{ID: "R-INPUT-002", Name: "Direct Input From User", Severity: model.SeverityMedium, Languages: []string{"r"}, Category: "INPUT", Enabled: true})
	Register(&Rule{ID: "R-RAND-001", Name: "Repeatable Pseudo-Random (set.seed)", Severity: model.SeverityMedium, Languages: []string{"r"}, Category: "RAND", Enabled: true})
	Register(&Rule{ID: "R-RAND-002", Name: "Repeatable Pseudo-Random (runif)", Severity: model.SeverityMedium, Languages: []string{"r"}, Category: "RAND", Enabled: true})
}
